name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v6

      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

      - name: test
        run: pnpm test

      - name: build
        run: pnpm build
